apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-credentials
  namespace: cloudflared
type: Opaque
stringData:
  credentials.json: ENC[AES256_GCM,data:eyJ0dW5uZWwiOiJleGFtcGxlIn0=,iv:IvExample=,tag:TagExample=,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w3q0u5l2d9k3ym8n0exampleexampleexampleexampleexamplex
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        ZXhhbXBsZVR1bm5lbENyZWRz
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k3sopsrecipientexampleexampleexampleexampleexamplehq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        ZXhhbXBsZVNlY29uZFR1bm5lbENyZWRz
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-07-01T00:00:00Z"
  mac: ENC[AES256_GCM,data:anotherMacExample=,iv:AnotherIv=,tag:AnotherTag=,type:str]
  version: 3.7.3
