apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    kustomize.config.k8s.io/behavior: replace
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:wkX0exampleu7b,iv:Qexample=,tag:jexample=,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w3q0u5l2d9k3ym8n0exampleexampleexampleexampleexamplex
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRlZC1kYXRhLXBheWxvYWQKZXhhbXBsZUVuY3J5cHRlZFN0cmluZwotLS0tLUVORCBBR0UgRU5DUllQVEVEIEZJTEUtLS0tLQo=
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k3sopsrecipientexampleexampleexampleexampleexamplehq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YW5vdGhlckV4YW1wbGVFbmNyeXB0ZWRTdHJpbmcKLS0tLS1FTkQgQUdFIEVOQ1JZUFRFRCBGSUxFLS0tLS0K
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-07-01T00:00:00Z"
  mac: ENC[AES256_GCM,data:mcExampleMac=,iv:RANDOMIVEXAMPLE=,tag:TAGEXAMPLE=,type:str]
  version: 3.7.3
