apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: k3s-traefik
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: sugarkube-staging-ingress-ha
spec:
  valuesContent: |-
    deployment:
      replicas: 2
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: traefik
            topologyKey: kubernetes.io/hostname
