apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 10m
  chart:
    spec:
      chart: cloudflared
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cloudflared-values
      valuesKey: values.yaml
