apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflared
      version: 1.20.2
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
  values:
    image:
      repository: cloudflare/cloudflared
    tunnelID: 11111111-1111-1111-1111-111111111111
    existingSecret: cloudflared-tunnel-credentials
    ingress:
      - hostname: apps.dev.sugarkube.cloud
        service: http://traefik.kube-system.svc.cluster.local:80
      - service: http_status:404
    metrics:
      enabled: true
