apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 30m
  releaseName: loki-stack
  chart:
    spec:
      chart: loki-stack
      version: 2.10.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  upgrade:
    remediation:
      retries: 3
  values:
    loki:
      isDefault: true
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 20Gi
    promtail:
      enabled: true
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
      extraScrapeConfigs: []
    grafana:
      enabled: false
    prometheus:
      enabled: false
