apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../platform
patchesStrategicMerge:
  - patches/kube-vip.yaml
  - patches/issuers.yaml
configMapGenerator:
  - name: cloudflared-settings
    namespace: cloudflared
    behavior: replace
    files:
      - values.yaml=config/cloudflared-values.yaml
