repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: local
    hooks:
      - id: run-checks
        name: run project checks
        entry: bash scripts/checks.sh
        language: python
        additional_dependencies:
          - flake8
          - isort
          - black
          - pytest
          - pytest-cov
          - coverage
          - pyspelling
          - linkchecker
          - requests
          - Flask
          - responses
        pass_filenames: false
