repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 1.8.0
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies: ['prettier@3.1.0']
        types_or: [markdown, yaml]
  - repo: local
    hooks:
      - id: run-checks
        name: run project checks
        entry: bash scripts/checks.sh
        language: python
        additional_dependencies:
          - flake8
          - isort
          - pytest
          - pytest-cov
          - coverage
          - pyspelling
          - linkchecker
          - requests
          - black
          - Flask
          - responses
          - requests-mock
        pass_filenames: false
