repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: local
    hooks:
      - id: build-stls
        name: build STL files
        entry: bash scripts/gen_stls.sh
        language: system
        pass_filenames: false
      - id: run-checks
        name: run project checks
        entry: bash scripts/checks.sh
        language: python
        additional_dependencies:
          - flake8
          - isort
          - black
          - pytest
          - linkchecker
          - requests
          - Flask
          - responses
        pass_filenames: false
