repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/adamchainz/pyproject-fmt
    rev: 0.9.1
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: '\.(yml|yaml|md)$'
  - repo: local
    hooks:
      - id: run-checks
        name: run project checks
        entry: bash scripts/checks.sh
        language: python
        additional_dependencies:
          - flake8
          - isort
          - black
          - pytest
          - pytest-cov
          - coverage
          - pyspelling
          - linkchecker
          - requests
          - requests-mock
          - Flask
          - responses
        pass_filenames: false
