apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  suspend: false
  install:
    createNamespace: false
  valuesFrom:
    - kind: ConfigMap
      name: external-dns-values
      valuesKey: values.yaml
