# token.place and dspace services; extend via # extra-start markers
version: '3'
services:
  # tokenplace-start
  tokenplace:
    build:
      context: ./token.place
      dockerfile: docker/Dockerfile.server
    ports:
      - "5000:5000"
    env_file:
      - token.place/.env
    restart: unless-stopped
  # tokenplace-end
  # dspace-start
  dspace:
    build:
      context: ./dspace/frontend
    working_dir: /opt/projects/dspace/frontend
    ports:
      - "3000:3000"
    env_file:
      - dspace/frontend/.env
    restart: unless-stopped
  # dspace-end
  # extra-start
  # Add additional services below
  # extra-end
