version: "3.8"
services:
  tokenplace:
    build:
      context: /opt/projects/token.place
      dockerfile: docker/Dockerfile.server
    ports:
      - "5000:5000"
    restart: unless-stopped
  dspace:
    build:
      context: /opt/projects/dspace/frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
# Add more services by extending this compose file.
