# token.place and dspace services; extend via # extra-start markers
version: '3'
services:
  # tokenplace-start
  tokenplace:
    build:
      context: /opt/projects/token.place
      dockerfile: docker/Dockerfile.server
    container_name: tokenplace
    ports:
      - "5000:5000"
    env_file:
      - /opt/projects/token.place/.env
    restart: unless-stopped
  # tokenplace-end
  # dspace-start
  dspace:
    build:
      context: /opt/projects/dspace/frontend
    working_dir: /opt/projects/dspace/frontend
    container_name: dspace
    ports:
      - "3000:3000"
    env_file:
      - /opt/projects/dspace/frontend/.env
    restart: unless-stopped
  # dspace-end
  # extra-start
  # Add additional services below. Example:
  # myapp:
  #   build:
  #     context: /opt/projects/myapp
  #   env_file:
  #     - /opt/projects/myapp/.env
  #   restart: unless-stopped
  # extra-end
