# token.place and dspace services; extend via # extra-start markers
version: '3'
services:
  # tokenplace-start
  tokenplace:
    build:
      context: /opt/projects/token.place
      dockerfile: docker/Dockerfile.server
    container_name: tokenplace
    ports:
      - "5000:5000"
    env_file:
      # Define TOKEN_PLACE_ENV, SUPABASE_URL, SUPABASE_KEY, PORT, NEXTAUTH_SECRET, NEXTAUTH_URL in this file
      - /opt/projects/token.place/.env
    restart: unless-stopped
  # tokenplace-end

  # dspace-start
  dspace:
    build:
      context: /opt/projects/dspace/frontend
    working_dir: /opt/projects/dspace/frontend
    container_name: dspace
    ports:
      - "3000:3000"
    env_file:
      # Define NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY, PORT in this file
      - /opt/projects/dspace/frontend/.env
    restart: unless-stopped
  # dspace-end

  # extra-start
  # Add additional services below and ensure matching .env entries in init-env.sh.
  # Example:
  # myapp:
  #   build:
  #     context: /opt/projects/myapp
  #   container_name: myapp
  #   ports:
  #     - "1234:1234"
  #   env_file:
  #     - /opt/projects/myapp/.env
  #   restart: unless-stopped
  # extra-end

  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: node-exporter
    restart: unless-stopped
    pid: host
    network_mode: host
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/kmsg
    network_mode: host
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  grafana-agent:
    image: grafana/agent:v0.39.4
    container_name: grafana-agent
    restart: unless-stopped
    depends_on:
      - node-exporter
      - cadvisor
    network_mode: host
    env_file:
      - /opt/projects/observability/grafana-agent.env
    command:
      - run
      - --config.file=/etc/grafana-agent/config.river
      - --config.expand-env
    volumes:
      - /opt/projects/observability/grafana-agent.river:/etc/grafana-agent/config.river:ro
      - /var/lib/grafana-agent:/var/lib/grafana-agent
      - /var/log:/var/log:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /run/log/journal:/run/log/journal:ro
      - /:/host:ro,rslave

  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    hostname: ${NETDATA_HOSTNAME:-sugarkube}
    restart: unless-stopped
    pid: host
    network_mode: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    env_file:
      - /opt/projects/observability/netdata.env
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
