#cloud-config
package_update: true
apt:
  sources:
    cloudflare:
      source: "deb [arch=arm64] https://pkg.cloudflare.com/ bookworm main"
      keyid: FBA8C0EE63617C5EED695C43254B391D8CACCBF8
      keyserver: https://keyserver.ubuntu.com
packages:
  - docker.io
  - docker-compose-plugin
  - curl
  - git
  - cloudflared
write_files:
  - path: /opt/sugarkube/.cloudflared.env
    permissions: '0600'
    content: |
      # Inject with TUNNEL_TOKEN env var or edit after boot
      TUNNEL_TOKEN=""
  - path: /opt/sugarkube/start-cloudflared.sh
    permissions: '0755'
    content: |
      #!/usr/bin/env bash
      set -e
      if ! grep -q 'TUNNEL_TOKEN=""' /opt/sugarkube/.cloudflared.env; then
        docker compose -f /opt/sugarkube/docker-compose.cloudflared.yml up -d
      else
        echo "TUNNEL_TOKEN not set; skipping tunnel start"
      fi
runcmd:
  - [bash, -c, 'usermod -aG docker pi']
  - [bash, -c, 'mkdir -p /opt/sugarkube']
  - [bash, -c, 'chown -R pi:pi /opt/sugarkube']
  - [systemctl, enable, --now, docker]
  - [/opt/sugarkube/start-cloudflared.sh]
