#cloud-config
package_update: true
package_upgrade: true
apt:
  sources:
    docker:
      # Official Docker repository for Engine and Compose
      source: "deb [arch=arm64] https://download.docker.com/linux/debian bookworm stable"
      key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        mQINBFit2ioBEADhWpZ8/wvZ6hUTiXOwQHXMAlaFHcPH9hAtr4F1y2+OYdbtMuth
        lqqwp028AqyY+PRfVMtSYMbjuQuu5byyKR01BbqYhuS3jtqQmljZ/bJvXqnmiVXh
        38UuLa+z077PxyxQhu5BbqntTPQMfiyqEiU+BKbq2WmANUKQf+1AmZY/IruOXbnq
        L4C1+gJ8vfmXQt99npCaxEjaNRVYfOS8QcixNzHUYnb6emjlANyEVlZzeqo7XKl7
        UrwV5inawTSzWNvtjEjj4nJL8NsLwscpLPQUhTQ+7BbQXAwAmeHCUTQIvvWXqw0N
        cmhh4HgeQscQHYgOJjjDVfoY5MucvglbIgCqfzAHW9jxmRL4qbMZj+b1XoePEtht
        ku4bIQN1X5P07fNWzlgaRL5Z4POXDDZTlIQ/El58j9kp4bnWRCJW0lya+f8ocodo
        vZZ+Doi+fy4D5ZGrL4XEcIQP/Lv5uFyf+kQtl/94VFYVJOleAv8W92KdgDkhTcTD
        G7c0tIkVEKNUq48b3aQ64NOZQW7fVjfoKwEZdOqPE72Pa45jrZzvUFxSpdiNk2tZ
        XYukHjlxxEgBdC/J3cMMNRE1F4NCA3ApfV1Y7/hTeOnmDuDYwr9/obA8t016Yljj
        q5rdkywPf4JF8mXUW5eCN1vAFHxeg9ZWemhBtQmGxXnw9M+z6hWwc6ahmwARAQAB
        tCtEb2NrZXIgUmVsZWFzZSAoQ0UgZGViKSA8ZG9ja2VyQGRvY2tlci5jb20+iQI3
        BBMBCgAhBQJYrefAAhsvBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAAoJEI2BgDwO
        v82IsskP/iQZo68flDQmNvn8X5XTd6RRaUH33kXYXquT6NkHJciS7E2gTJmqvMqd
        tI4mNYHCSEYxI5qrcYV5YqX9P6+Ko+vozo4nseUQLPH/ATQ4qL0Zok+1jkag3Lgk
        jonyUf9bwtWxFp05HC3GMHPhhcUSexCxQLQvnFWXD2sWLKivHp2fT8QbRGeZ+d3m
        6fqcd5Fu7pxsqm0EUDK5NL+nPIgYhN+auTrhgzhK1CShfGccM/wfRlei9Utz6p9P
        XRKIlWnXtT4qNGZNTN0tR+NLG/6Bqd8OYBaFAUcue/w1VW6JQ2VGYZHnZu9S8LMc
        FYBa5Ig9PxwGQOgq6RDKDbV+PqTQT5EFMeR1mrjckk4DQJjbxeMZbiNMG5kGECA8
        g383P3elhn03WGbEEa4MNc3Z4+7c236QI3xWJfNPdUbXRaAwhy/6rTSFbzwKB0Jm
        ebwzQfwjQY6f55MiI/RqDCyuPj3r3jyVRkK86pQKBAJwFHyqj9KaKXMZjfVnowLh
        9svIGfNbGHpucATqREvUHuQbNnqkCx8VVhtYkhDb9fEP2xBu5VvHbR+3nfVhMut5
        G34Ct5RS7Jt6LIfFdtcn8CaSas/l1HbiGeRgc70X/9aYx/V/CEJv0lIe8gP6uDoW
        FPIZ7d6vH+Vro6xuWEGiuMaiznap2KhZmpkgfupyFmplh0s6knymuQINBFit2ioB
        EADneL9S9m4vhU3blaRjVUUyJ7b/qTjcSylvCH5XUE6R2k+ckEZjfAMZPLpO+/tF
        M2JIJMD4SifKuS3xck9KtZGCufGmcwiLQRzeHF7vJUKrLD5RTkNi23ydvWZgPjtx
        Q+DTT1Zcn7BrQFY6FgnRoUVIxwtdw1bMY/89rsFgS5wwuMESd3Q2RYgb7EOFOpnu
        w6da7WakWf4IhnF5nsNYGDVaIHzpiqCl+uTbf1epCjrOlIzkZ3Z3Yk5CM/TiFzPk
        z2lLz89cpD8U+NtCsfagWWfjd2U3jDapgH+7nQnCEWpROtzaKHG6lA3pXdix5zG8
        eRc6/0IbUSWvfjKxLLPfNeCS2pCL3IeEI5nothEEYdQH6szpLog79xB9dVnJyKJb
        VfxXnseoYqVrRz2VVbUI5Blwm6B40E3eGVfUQWiux54DspyVMMk41Mx7QJ3iynIa
        1N4ZAqVMAEruyXTRTxc9XW0tYhDMA/1GYvz0EmFpm8LzTHA6sFVtPm/ZlNCX6P1X
        zJwrv7DSQKD6GGlBQUX+OeEJ8tTkkf8QTJSPUdh8P8YxDFS5EOGAvhhpMBYD42kQ
        pqXjEC+XcycTvGI7impgv9PDY1RCC1zkBjKPa120rNhv/hkVk/YhuGoajoHyy4h7
        ZQopdcMtpN2dgmhEegny9JCSwxfQmQ0zK0g7m6SHiKMwjwARAQABiQQ+BBgBCAAJ
        BQJYrdoqAhsCAikJEI2BgDwOv82IwV0gBBkBCAAGBQJYrdoqAAoJEH6gqcPyc/zY
        1WAP/2wJ+R0gE6qsce3rjaIz58PJmc8goKrir5hnElWhPgbq7cYIsW5qiFyLhkdp
        YcMmhD9mRiPpQn6Ya2w3e3B8zfIVKipbMBnke/ytZ9M7qHmDCcjoiSmwEXN3wKYI
        mD9VHONsl/CG1rU9Isw1jtB5g1YxuBA7M/m36XN6x2u+NtNMDB9P56yc4gfsZVES
        KA9v+yY2/l45L8d/WUkUi0YXomn6hyBGI7JrBLq0CX37GEYP6O9rrKipfz73XfO7
        JIGzOKZlljb/D9RX/g7nRbCn+3EtH7xnk+TK/50euEKw8SMUg147sJTcpQmv6UzZ
        cM4JgL0HbHVCojV4C/plELwMddALOFeYQzTif6sMRPf+3DSj8frbInjChC3yOLy0
        6br92KFom17EIj2CAcoeq7UPhi2oouYBwPxh5ytdehJkoo+sN7RIWua6P2WSmon5
        U888cSylXC0+ADFdgLX9K2zrDVYUG1vo8CX0vzxFBaHwN6Px26fhIT1/hYUHQR1z
        VfNDcyQmXqkOnZvvoMfz/Q0s9BhFJ/zU6AgQbIZE/hm1spsfgvtsD1frZfygXJ9f
        irP+MSAI80xHSf91qSRZOj4Pl3ZJNbq4yYxv0b1pkMqeGdjdCYhLU+LZ4wbQmpCk
        SVe2prlLureigXtmZfkqevRz7FrIZiu9ky8wnCAPwC7/zmS18rgP/17bOtL4/iIz
        QhxAAoAMWVrGyJivSkjhSGx1uCojsWfsTAm11P7jsruIL61ZzMUVE2aM3Pmj5G+W
        9AcZ58Em+1WsVnAXdUR//bMmhyr8wL/G1YO1V3JEJTRdxsSxdYa4deGBBY/Adpsw
        24jxhOJR+lsJpqIUeb999+R8euDhRHG9eFO7DRu6weatUJ6suupoDTRWtr/4yGqe
        dKxV3qQhNLSnaAzqW/1nA3iUB4k7kCaKZxhdhDbClf9P37qaRW467BLCVO/coL3y
        Vm50dwdrNtKpMBh3ZpbB1uJvgi9mXtyBOMJ3v8RZeDzFiG8HdCtg9RvIt/AIFoHR
        H3S+U79NT6i0KPzLImDfs8T7RlpyuMc4Ufs8ggyg9v3Ae6cN3eQyxcK3w0cbBwsh
        /nQNfsA6uu+9H7NhbehBMhYnpNZyrHzCmzyXkauwRAqoCbGCNykTRwsur9gS41TQ
        M8ssD1jFheOJf3hODnkKU+HKjvMROl1DK7zdmLdNzA1cvtZH/nCC9KPj1z8QC47S
        xx+dTZSx4ONAhwbS/LN3PoKtn8LPjY9NP9uDWI+TWYquS2U+KHDrBDlsgozDbs/O
        jCxcpDzNmXpWQHEtHU7649OXHP7UeNST1mCUCH5qdank0V1iejF6/CfTFU4MfcrG
        YT90qFF93M3v01BbxP+EIY2/9tiIPbrd
        =0YYh
        -----END PGP PUBLIC KEY BLOCK-----
    cloudflare:
      source: "deb [arch=arm64] https://pkg.cloudflare.com/ bookworm main"
      key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        Comment: Hostname:
        Version: Hockeypuck 2.2

        xsBNBFTJNTUBCADZtil+vA5moao8PseavB1lzayrpuRhANlLRtaXGd1mj4JmZRoi
        2Ns8WyZpuOaPItOALg7aifBwKwXeLIB6OiCNTxry2gs9SOx57sn+zYiFNKJYK+v3
        qJAJ8qGm8w6E1x32BYeO3RuZt2VHGoYlRKLLVgiY5wmZg6xj6R0YvfxZ9UQa24wu
        V4BnPlpX4g1uSqJ8anSyRSdFb7DYf+28L4JNkl5mCW6q0HSB+/yfLXk1tC2jqPyc
        e0zzfH9J8homH4YquZsWkrwxkJKdIalqjl4VLamLYiauhJN+5Jf0HxOgcXKQCyql
        0m7Wxu6aaSu/0qLo9wRIT06jvyh77HMKNdsnABEBAAHNM0Nsb3VkRmxhcmUgU29m
        dHdhcmUgUGFja2FnaW5nIDxoZWxwQGNsb3VkZmxhcmUuY29tPsLAeAQTAQIAIgUC
        VMk1NQIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQJUs5HYysy/gHqwgA
        japcx0rcEiH0g5/4URaW05wxKuIyCwbtsihDd2cNW6RF8XvEB9cWnSbE/HEN9I2W
        tePIjQRag7k6wPU1GIrQxnhjK/Dw4wpwppCAVRajCgxWnxJ34zmvMpx9yRDk2+aW
        vaBV0VwXCRTro/qleyb3IWokorxjqe8hEc2qVoNwkysKvB3ZTL7hxVzeMvTKTvti
        A84+9h4In2V4XaqTBgEPtmINVJoorEUN5US6xqWX+25YGei459TvBRHf5YQfYL3N
        dZkmPzbTl7Em3zwbNXKvfzwkmRG2QABdHCe0hhhJLjjWuCJ3vObB+6QxInbm9uEp
        kf86007RP1cWqCpwKpsUmsLBcwQQAQgAHRYhBJLy0eRsY3I2f9hGiqNEX0m6pO8f
        BQJcl26XAAoJEKNEX0m6pO8fgSwP/jngqRUsCBVGgK0qUD1kiRJ0nuYUExhKUczm
        2tU7rgxkmObd2X+scLxMvJVE151qN30jsC9xIW6kOikXAnC4xzWOeLWf05xNfLBp
        +HiysNCogRRHHsmrMrv09mQiV+5l0yD5Zdlo6m9m0xKzT3WXVlVzOYCMjd87yy+8
        AYKpW7my7LnZZDJsRRY1K8r07t3Eei3UNWIN7z4Zf4teznaDR0HXZMWnSxDqD4m3
        8KlIJP2/MGhpBp4YUWIvqYdtWM4dwxpm/hyfJ5cptlOLLk6pgeeWPz3y8sOmj4wB
        MQwRogc/0cIRSm5Ezg5SX/+R0jLZT7af2KVFh4JwWco0cDmPy7AZaeUj7/0I44jh
        SupQrobEEucmaorFZG8mpDN1iKUo9N2acPtrqF17aY7nOzKBcoof1ChqJI1SGzvF
        TNp+i6i7tGR10a3gSooqs7+oVzT/DqEBSskuDx7bjIwVLVAz3sQ5ZwHsax953C24
        MFD4KYQ15HpXIR+lLL2W6UlVGHsOwOGKdxOaEFMkqD73q8dCaomtW6VKgAQQZaSR
        1/1DEb3I7P4Tfb2Lkx61e70vg7/X36XKg18vWwBRJX4xAhVDpz6Eb/Mv/fLwCHlK
        YJ5Lnr/he8DhrSqpYXqgmcjV9W5zTwzlMTdNr0lrIspMAj/fD0tocREX0CQMYi4T
        biai+WybwnUEEBYKAB0WIQSYy/xGsyIgBiucUodOBhu4NhO0UAUCZTrzvwAKCRBO
        Bhu4NhO0UMoMAQCk2Lk06imV4BIKft46wKTEz8K3JCJYZ37t1KUGAdNXPgD/fK4P
        u0hL61Hn0rmt4Z4aa6PdbFSVn7QM5c0Vo8NBgALCdQQQFgoAHRYhBJh3tCsOCkkv
        D3ul2hh4ijHB+YWMBQJlPz85AAoJEBh4ijHB+YWM0qsA/AuegJgwUKQJieiuYtg2
        k3zJU9BYlDr2HVFdKoM52zgrAQDlZP3Gti63f3e/TQ9vl1ooGa+ScG3KZr66lzXa
        vPVkBcJ1BBAWCgAdFiEEVRHGqq12f40yk4+s14zy1TLogdwFAmcLDhUACgkQ14zy
        1TLogdwu6gD9ET+5n75SQzZ+vHfWMOIlSqmmUwD7laLaokSdhIrQyMUA/iDwRm45
        3ma+4647bPi5LFat/J5KDkqpIH0kxkUy6FIAwngEMBYKACAWIQRVEcaqrXZ/jTKT
        j6zXjPLVMuiB3AUCZwsOigIdAAAKCRDXjPLVMuiB3PckAQDIzSwZtdKRv40QLiXj
        3N8toK5GrzkqlL3nCOsGitJ09wD/UE3slJV+TRET7FovZUItFI7XXRxvgYd79NsL
        8a3MmQI=
        =fCJE
        -----END PGP PUBLIC KEY BLOCK-----
packages:
  - ca-certificates
  - curl
  - gnupg
  - git
  - cloudflared
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
write_files:
  - path: /opt/sugarkube/.cloudflared.env
    permissions: '0600'
    content: |
      # Inject with TUNNEL_TOKEN or TUNNEL_TOKEN_FILE env var or edit after boot
      TUNNEL_TOKEN=""
  - path: /opt/sugarkube/docker-compose.cloudflared.yml
    permissions: '0644'
    content: |
      services:
        tunnel:
          image: cloudflare/cloudflared:latest
          restart: unless-stopped
          command: tunnel run
          env_file:
            - /opt/sugarkube/.cloudflared.env
  - path: /etc/systemd/system/cloudflared-compose.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Cloudflare Tunnel via docker compose
      Requires=docker.service
      After=docker.service network-online.target
      Wants=network-online.target

      [Service]
      Type=oneshot
      WorkingDirectory=/opt/sugarkube
      ExecStart=/usr/bin/docker compose -f /opt/sugarkube/docker-compose.cloudflared.yml up -d
      ExecStop=/usr/bin/docker compose -f /opt/sugarkube/docker-compose.cloudflared.yml down
      RemainAfterExit=yes
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
  - path: /etc/apt/apt.conf.d/80-retries
    permissions: '0644'
    content: |
      Acquire::Retries "5";
      Acquire::http::Timeout "30";
      Acquire::https::Timeout "30";
      APT::Get::Fix-Missing "true";
  - path: /etc/systemd/journald.conf.d/persistent.conf
    permissions: '0644'
    content: |
      [Journal]
      Storage=persistent
      SystemMaxUse=200M
  # projects-start
  - path: /etc/systemd/system/projects-compose.service
    permissions: '0644'
    content: |
      [Unit]
      Description=token.place and dspace via docker compose
      Requires=docker.service
      After=docker.service network-online.target
      Wants=network-online.target

      [Service]
      Type=oneshot
      WorkingDirectory=/opt/projects
      ExecStartPre=/opt/projects/init-env.sh
      ExecStart=/usr/bin/docker compose -f docker-compose.yml up -d
      ExecStop=/usr/bin/docker compose -f docker-compose.yml down
      RemainAfterExit=yes
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
  # projects-end
runcmd:
  - [bash, -c, 'id pi >/dev/null 2>&1 && usermod -aG docker pi || true']
  - [bash, -c, 'mkdir -p /opt/sugarkube']
  - [bash, -c, 'id pi >/dev/null 2>&1 && chown -R pi:pi /opt/sugarkube || true']
  - [bash, -c, 'mkdir -p /var/log/journal && systemctl restart systemd-journald']
  - [systemctl, daemon-reexec]   # reload systemd units
  - [systemctl, enable, --now, docker]
  - [/opt/projects/start-projects.sh]  # projects-runcmd
  - [bash, -c, 'apt-get autoremove -y']
  - [bash, -c, 'apt-get clean && rm -rf /var/lib/apt/lists/*']
  - |
      if grep -q 'TUNNEL_TOKEN=""' /opt/sugarkube/.cloudflared.env; then
        echo 'Cloudflare token missing; not starting tunnel'
      else
        systemctl enable --now cloudflared-compose.service
      fi
