#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose-plugin
  - git
  - cloudflared
write_files:
  - path: /opt/sugarkube/docker-compose.cloudflared.yml
    permissions: '0644'
    content: |
      services:
        tunnel:
          image: cloudflare/cloudflared:latest
          restart: unless-stopped
          command: tunnel run
          env_file:
            - /opt/sugarkube/.cloudflared.env
runcmd:
  - [bash, -c, 'usermod -aG docker pi']
  - [bash, -c, 'touch /opt/sugarkube/.cloudflared.env']
  - [bash, -c, 'chown -R pi:pi /opt/sugarkube']
