#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose-plugin
  - curl
  - git
  - cloudflared
runcmd:
  - [bash, -c, 'usermod -aG docker pi']
  - [bash, -c, 'mkdir -p /opt/sugarkube']
  - [bash, -c, 'curl -fsSL https://raw.githubusercontent.com/futuroptimist/sugarkube/main/scripts/cloud-init/docker-compose.cloudflared.yml -o /opt/sugarkube/docker-compose.cloudflared.yml']
  - [bash, -c, 'touch /opt/sugarkube/.cloudflared.env']
  - [bash, -c, 'chown -R pi:pi /opt/sugarkube']
