#cloud-config
package_update: true
package_upgrade: true
apt:
  sources:
    cloudflare:
      source: "deb [arch=arm64] https://pkg.cloudflare.com/ bookworm main"
      keyid: FBA8C0EE63617C5EED695C43254B391D8CACCBF8
      keyserver: https://keyserver.ubuntu.com
packages:
  - docker.io
  - docker-compose-plugin
  - curl
  - git
  - cloudflared
write_files:
  - path: /opt/sugarkube/.cloudflared.env
    permissions: '0600'
    content: |
      # Inject with TUNNEL_TOKEN or TUNNEL_TOKEN_FILE env var or edit after boot
      TUNNEL_TOKEN=""
  - path: /opt/sugarkube/docker-compose.cloudflared.yml
    permissions: '0644'
    content: |
      services:
        tunnel:
          image: cloudflare/cloudflared:latest
          restart: unless-stopped
          command: tunnel run
          env_file:
            - /opt/sugarkube/.cloudflared.env
  - path: /etc/systemd/system/cloudflared-compose.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Cloudflare Tunnel via docker compose
      Requires=docker.service
      After=docker.service network-online.target
      Wants=network-online.target

      [Service]
      Type=oneshot
      WorkingDirectory=/opt/sugarkube
      ExecStart=/usr/bin/docker compose -f /opt/sugarkube/docker-compose.cloudflared.yml up -d
      ExecStop=/usr/bin/docker compose -f /opt/sugarkube/docker-compose.cloudflared.yml down
      RemainAfterExit=yes
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
  - path: /etc/apt/apt.conf.d/80-retries
    permissions: '0644'
    content: |
      Acquire::Retries "5";
      Acquire::http::Timeout "30";
      Acquire::https::Timeout "30";
      APT::Get::Fix-Missing "true";
  - path: /etc/systemd/system/projects-compose.service
    permissions: '0644'
    content: |
      [Unit]
      Description=token.place and dspace via docker compose
      Requires=docker.service
      After=docker.service network-online.target
      Wants=network-online.target

      [Service]
      Type=oneshot
      WorkingDirectory=/opt/projects
      ExecStartPre=/opt/projects/init-env.sh
      ExecStart=/usr/bin/docker compose -f docker-compose.yml up -d
      ExecStop=/usr/bin/docker compose -f docker-compose.yml down
      RemainAfterExit=yes
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
runcmd:
  - [bash, -c, 'id pi >/dev/null 2>&1 && usermod -aG docker pi || true']
  - [bash, -c, 'mkdir -p /opt/sugarkube']
  - [bash, -c, 'id pi >/dev/null 2>&1 && chown -R pi:pi /opt/sugarkube || true']
  - [systemctl, daemon-reexec]   # reload systemd units
  - [systemctl, enable, --now, docker]
  - [/opt/projects/start-projects.sh]  # projects-runcmd
  - [bash, -c, 'apt-get clean && rm -rf /var/lib/apt/lists/*']
  - |
      if grep -q 'TUNNEL_TOKEN=""' /opt/sugarkube/.cloudflared.env; then
        echo 'Cloudflare token missing; not starting tunnel'
      else
        systemctl enable --now cloudflared-compose.service
      fi
