#cloud-config
package_update: true
package_upgrade: true
apt:
  sources:
    cloudflare:
      source: "deb [arch=arm64] https://pkg.cloudflare.com/ bookworm main"
      keyid: FBA8C0EE63617C5EED695C43254B391D8CACCBF8
      keyserver: https://keyserver.ubuntu.com
packages:
  - docker.io
  - docker-compose-plugin
  - curl
  - git
  - cloudflared
write_files:
  - path: /opt/sugarkube/.cloudflared.env
    permissions: '0600'
    content: |
      # Inject with TUNNEL_TOKEN or TUNNEL_TOKEN_FILE env var or edit after boot
      TUNNEL_TOKEN=""
  - path: /etc/systemd/system/cloudflared-compose.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Cloudflare Tunnel via docker compose
      Requires=docker.service
      After=docker.service network-online.target
      Wants=network-online.target

      [Service]
      Type=oneshot
      WorkingDirectory=/opt/sugarkube
      ExecStart=/usr/bin/docker compose -f /opt/sugarkube/docker-compose.cloudflared.yml up -d
      ExecStop=/usr/bin/docker compose -f /opt/sugarkube/docker-compose.cloudflared.yml down
      RemainAfterExit=yes
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
runcmd:
  - [bash, -c, 'id pi >/dev/null 2>&1 && usermod -aG docker pi || true']
  - [bash, -c, 'mkdir -p /opt/sugarkube']
  - [bash, -c, 'id pi >/dev/null 2>&1 && chown -R pi:pi /opt/sugarkube || true']
  - [systemctl, enable, --now, docker]
  - ["/usr/local/sbin/install_repo_service.sh",
     "tokenplace",
     "/opt/projects/token.place",
     "bash /usr/local/sbin/start_tokenplace.sh",
     "docker rm -f tokenplace"]
  - ["/usr/local/sbin/install_repo_service.sh",
     "dspace",
     "/opt/projects/dspace/frontend",
     "bash /usr/local/sbin/start_dspace.sh",
     "docker compose down"]
  - [bash, -c, 'apt-get clean']
  - |
      if grep -q 'TUNNEL_TOKEN=""' /opt/sugarkube/.cloudflared.env; then
        echo 'Cloudflare token missing; not starting tunnel'
      else
        systemctl enable --now cloudflared-compose.service
      fi
