#cloud-config
package_update: true
package_upgrade: true
apt:
  sources:
    docker:
      # Official Docker repository for Engine and Compose
      source: "deb [arch=arm64] https://download.docker.com/linux/debian bookworm stable"
      keyid: 8D81803C0EBFCD88
      keyserver: https://keyserver.ubuntu.com
    cloudflare:
      source: "deb [arch=arm64] https://pkg.cloudflare.com/ bookworm main"
      key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        mQINBFit2ioBEADhWpZ8/wvZ6hUTiXOwQHXMAlaFHcPH9hAtr4F1y2+OYdbtMuth
        lqqwp028AqyY+PRfVMtSYMbjuQuu5byyKR01BbqYhuS3jtqQmljZ/bJvXqnmiVXh
        38UuLa+z077PxyxQhu5BbqntTPQMfiyqEiU+BKbq2WmANUKQf+1AmZY/IruOXbnq
        L4C1+gJ8vfmXQt99npCaxEjaNRVYfOS8QcixNzHUYnb6emjlANyEVlZzeqo7XKl7
        UrwV5inawTSzWNvtjEjj4nJL8NsLwscpLPQUhTQ+7BbQXAwAmeHCUTQIvvWXqw0N
        cmhh4HgeQscQHYgOJjjDVfoY5MucvglbIgCqfzAHW9jxmRL4qbMZj+b1XoePEtht
        ku4bIQN1X5P07fNWzlgaRL5Z4POXDDZTlIQ/El58j9kp4bnWRCJW0lya+f8ocodo
        vZZ+Doi+fy4D5ZGrL4XEcIQP/Lv5uFyf+kQtl/94VFYVJOleAv8W92KdgDkhTcTD
        G7c0tIkVEKNUq48b3aQ64NOZQW7fVjfoKwEZdOqPE72Pa45jrZzvUFxSpdiNk2tZ
        XYukHjlxxEgBdC/J3cMMNRE1F4NCA3ApfV1Y7/hTeOnmDuDYwr9/obA8t016Yljj
        q5rdkywPf4JF8mXUW5eCN1vAFHxeg9ZWemhBtQmGxXnw9M+z6hWwc6ahmwARAQAB
        tCtEb2NrZXIgUmVsZWFzZSAoQ0UgZGViKSA8ZG9ja2VyQGRvY2tlci5jb20+iQI3
        BBMBCgAhBQJYrefAAhsvBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAAoJEI2BgDwO
        v82IsskP/iQZo68flDQmNvn8X5XTd6RRaUH33kXYXquT6NkHJciS7E2gTJmqvMqd
        tI4mNYHCSEYxI5qrcYV5YqX9P6+Ko+vozo4nseUQLPH/ATQ4qL0Zok+1jkag3Lgk
        jonyUf9bwtWxFp05HC3GMHPhhcUSexCxQLQvnFWXD2sWLKivHp2fT8QbRGeZ+d3m
        6fqcd5Fu7pxsqm0EUDK5NL+nPIgYhN+auTrhgzhK1CShfGccM/wfRlei9Utz6p9P
        XRKIlWnXtT4qNGZNTN0tR+NLG/6Bqd8OYBaFAUcue/w1VW6JQ2VGYZHnZu9S8LMc
        FYBa5Ig9PxwGQOgq6RDKDbV+PqTQT5EFMeR1mrjckk4DQJjbxeMZbiNMG5kGECA8
        g383P3elhn03WGbEEa4MNc3Z4+7c236QI3xWJfNPdUbXRaAwhy/6rTSFbzwKB0Jm
        ebwzQfwjQY6f55MiI/RqDCyuPj3r3jyVRkK86pQKBAJwFHyqj9KaKXMZjfVnowLh
        9svIGfNbGHpucATqREvUHuQbNnqkCx8VVhtYkhDb9fEP2xBu5VvHbR+3nfVhMut5
        G34Ct5RS7Jt6LIfFdtcn8CaSas/l1HbiGeRgc70X/9aYx/V/CEJv0lIe8gP6uDoW
        FPIZ7d6vH+Vro6xuWEGiuMaiznap2KhZmpkgfupyFmplh0s6knymuQINBFit2ioB
        EADneL9S9m4vhU3blaRjVUUyJ7b/qTjcSylvCH5XUE6R2k+ckEZjfAMZPLpO+/tF
        M2JIJMD4SifKuS3xck9KtZGCufGmcwiLQRzeHF7vJUKrLD5RTkNi23ydvWZgPjtx
        Q+DTT1Zcn7BrQFY6FgnRoUVIxwtdw1bMY/89rsFgS5wwuMESd3Q2RYgb7EOFOpnu
        w6da7WakWf4IhnF5nsNYGDVaIHzpiqCl+uTbf1epCjrOlIzkZ3Z3Yk5CM/TiFzPk
        z2lLz89cpD8U+NtCsfagWWfjd2U3jDapgH+7nQnCEWpROtzaKHG6lA3pXdix5zG8
        eRc6/0IbUSWvfjKxLLPfNeCS2pCL3IeEI5nothEEYdQH6szpLog79xB9dVnJyKJb
        VfxXnseoYqVrRz2VVbUI5Blwm6B40E3eGVfUQWiux54DspyVMMk41Mx7QJ3iynIa
        1N4ZAqVMAEruyXTRTxc9XW0tYhDMA/1GYvz0EmFpm8LzTHA6sFVtPm/ZlNCX6P1X
        zJwrv7DSQKD6GGlBQUX+OeEJ8tTkkf8QTJSPUdh8P8YxDFS5EOGAvhhpMBYD42kQ
        pqXjEC+XcycTvGI7impgv9PDY1RCC1zkBjKPa120rNhv/hkVk/YhuGoajoHyy4h7
        ZQopdcMtpN2dgmhEegny9JCSwxfQmQ0zK0g7m6SHiKMwjwARAQABiQQ+BBgBCAAJ
        BQJYrdoqAhsCAikJEI2BgDwOv82IwV0gBBkBCAAGBQJYrdoqAAoJEH6gqcPyc/zY
        1WAP/2wJ+R0gE6qsce3rjaIz58PJmc8goKrir5hnElWhPgbq7cYIsW5qiFyLhkdp
        YcMmhD9mRiPpQn6Ya2w3e3B8zfIVKipbMBnke/ytZ9M7qHmDCcjoiSmwEXN3wKYI
        mD9VHONsl/CG1rU9Isw1jtB5g1YxuBA7M/m36XN6x2u+NtNMDB9P56yc4gfsZVES
        KA9v+yY2/l45L8d/WUkUi0YXomn6hyBGI7JrBLq0CX37GEYP6O9rrKipfz73XfO7
        JIGzOKZlljb/D9RX/g7nRbCn+3EtH7xnk+TK/50euEKw8SMUg147sJTcpQmv6UzZ
        cM4JgL0HbHVCojV4C/plELwMddALOFeYQzTif6sMRPf+3DSj8frbInjChC3yOLy0
        6br92KFom17EIj2CAcoeq7UPhi2oouYBwPxh5ytdehJkoo+sN7RIWua6P2WSmon5
        U888cSylXC0+ADFdgLX9K2zrDVYUG1vo8CX0vzxFBaHwN6Px26fhIT1/hYUHQR1z
        VfNDcyQmXqkOnZvvoMfz/Q0s9BhFJ/zU6AgQbIZE/hm1spsfgvtsD1frZfygXJ9f
        irP+MSAI80xHSf91qSRZOj4Pl3ZJNbq4yYxv0b1pkMqeGdjdCYhLU+LZ4wbQmpCk
        SVe2prlLureigXtmZfkqevRz7FrIZiu9ky8wnCAPwC7/zmS18rgP/17bOtL4/iIz
        QhxAAoAMWVrGyJivSkjhSGx1uCojsWfsTAm11P7jsruIL61ZzMUVE2aM3Pmj5G+W
        9AcZ58Em+1WsVnAXdUR//bMmhyr8wL/G1YO1V3JEJTRdxsSxdYa4deGBBY/Adpsw
        24jxhOJR+lsJpqIUeb999+R8euDhRHG9eFO7DRu6weatUJ6suupoDTRWtr/4yGqe
        dKxV3qQhNLSnaAzqW/1nA3iUB4k7kCaKZxhdhDbClf9P37qaRW467BLCVO/coL3y
        Vm50dwdrNtKpMBh3ZpbB1uJvgi9mXtyBOMJ3v8RZeDzFiG8HdCtg9RvIt/AIFoHR
        H3S+U79NT6i0KPzLImDfs8T7RlpyuMc4Ufs8ggyg9v3Ae6cN3eQyxcK3w0cbBwsh
        /nQNfsA6uu+9H7NhbehBMhYnpNZyrHzCmzyXkauwRAqoCbGCNykTRwsur9gS41TQ
        M8ssD1jFheOJf3hODnkKU+HKjvMROl1DK7zdmLdNzA1cvtZH/nCC9KPj1z8QC47S
        xx+dTZSx4ONAhwbS/LN3PoKtn8LPjY9NP9uDWI+TWYquS2U+KHDrBDlsgozDbs/O
        jCxcpDzNmXpWQHEtHU7649OXHP7UeNST1mCUCH5qdank0V1iejF6/CfTFU4MfcrG
        YT90qFF93M3v01BbxP+EIY2/9tiIPbrd
        =0YYh
        -----END PGP PUBLIC KEY BLOCK-----
packages:
  - ca-certificates
  - curl
  - gnupg
  - git
  - cloudflared
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - helm
write_files:
  - path: /opt/sugarkube/.cloudflared.env
    permissions: '0600'
    content: |
      # Inject with TUNNEL_TOKEN or TUNNEL_TOKEN_FILE env var or edit after boot
      TUNNEL_TOKEN=""
  - path: /opt/sugarkube/docker-compose.cloudflared.yml
    permissions: '0644'
    content: |
      services:
        tunnel:
          image: cloudflare/cloudflared:latest
          restart: unless-stopped
          command: tunnel run
          env_file:
            - /opt/sugarkube/.cloudflared.env
  - path: /etc/systemd/system/cloudflared-compose.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Cloudflare Tunnel via docker compose
      Requires=docker.service
      After=docker.service network-online.target
      Wants=network-online.target

      [Service]
      Type=oneshot
      WorkingDirectory=/opt/sugarkube
      ExecStart=/usr/bin/docker compose -f /opt/sugarkube/docker-compose.cloudflared.yml up -d
      ExecStop=/usr/bin/docker compose -f /opt/sugarkube/docker-compose.cloudflared.yml down
      RemainAfterExit=yes
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
  - path: /etc/apt/apt.conf.d/80-retries
    permissions: '0644'
    content: |
      Acquire::Retries "5";
      Acquire::http::Timeout "30";
      Acquire::https::Timeout "30";
      APT::Get::Fix-Missing "true";
  - path: /etc/systemd/journald.conf.d/persistent.conf
    permissions: '0644'
    content: |
      [Journal]
      Storage=persistent
      SystemMaxUse=200M
  - path: /etc/sugarkube/telemetry.env
    permissions: '0600'
    content: |
      # Set SUGARKUBE_TELEMETRY_ENABLE="true" to publish anonymized health telemetry.
      SUGARKUBE_TELEMETRY_ENABLE="false"
      # Configure the HTTPS endpoint that receives telemetry payloads.
      SUGARKUBE_TELEMETRY_ENDPOINT=""
      # Optional bearer token included in Authorization headers.
      # Uncomment and set SUGARKUBE_TELEMETRY_TOKEN once you have a bearer token.
      # Optional salt mixed into the hashed instance identifier.
      SUGARKUBE_TELEMETRY_SALT=""
      # Optional comma-separated labels (e.g., "lab,pi-a") for dashboards.
      SUGARKUBE_TELEMETRY_TAGS=""
      # HTTP timeout in seconds for uploads.
      SUGARKUBE_TELEMETRY_TIMEOUT="10"
      # Timeout in seconds for pi_node_verifier execution.
      SUGARKUBE_TELEMETRY_VERIFIER_TIMEOUT="180"
  - path: /etc/systemd/system/sugarkube-telemetry.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Publish sugarkube verifier telemetry
      After=network-online.target
      Wants=network-online.target
      ConditionPathExists=/usr/local/bin/sugarkube-publish-telemetry

      [Service]
      Type=oneshot
      EnvironmentFile=-/etc/sugarkube/telemetry.env
      ExecStart=/usr/local/bin/sugarkube-publish-telemetry
      Nice=10
      IOSchedulingClass=best-effort
      IOSchedulingPriority=6

      [Install]
      WantedBy=multi-user.target
  - path: /etc/systemd/system/sugarkube-helm-bundles.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Apply pinned Helm bundles once k3s is ready
      Requires=k3s-ready.target
      After=k3s-ready.target
      ConditionPathExists=/opt/sugarkube/apply-helm-bundles.sh
      OnFailure=sugarkube-self-heal@%n.service
      OnFailureJobMode=replace-irreversibly

      [Service]
      Type=oneshot
      ExecStart=/opt/sugarkube/apply-helm-bundles.sh
      # Allow Helm bundles to wait for rollouts and health checks without the
      # unit timing out while the helper is still working.
      TimeoutStartSec=infinity
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target
  - path: /etc/sugarkube/helm-bundles.d/README
    permissions: '0644'
    content: |
      # Sugarkube Helm bundles
      #
      # Drop `*.env` files in this directory to have `/opt/sugarkube/apply-helm-bundles.sh`
      # automatically install pinned Helm charts after k3s becomes Ready.
      # Each file exports key=value pairs, for example:
      #
      #   RELEASE=my-addon
      #   CHART=oci://registry.example.com/addons/my-addon
      #   VERSION=1.2.3
      #   NAMESPACE=addons
      #   WAIT_TARGETS=deployment.apps/addon-controller
      #   VALUES_FILES=/opt/sugarkube/helm-values/addon.yaml
      #
      # Optional keys:
      #   EXTRA_HELM_ARGS="--set key=value --timeout 10m"
      #   HEALTHCHECK_CMD="kubectl get pods -n addons"
      #   HEALTHCHECK_TIMEOUT=600
      #   NOTES="Appears in first-boot report entries"
      #
      # Copy values files into `/opt/sugarkube/helm-values/` or any readable path.
      # The helper logs to `/var/log/sugarkube/helm-bundles.log` and writes
      # per-release reports under `/boot/first-boot-report/helm-bundles/` when the
      # boot partition is mounted.
  - path: /etc/systemd/system/sugarkube-telemetry.timer
    permissions: '0644'
    content: |
      [Unit]
      Description=Run sugarkube telemetry publisher periodically

      [Timer]
      OnBootSec=5min
      OnUnitActiveSec=1h
      AccuracySec=5min
      Persistent=true

      [Install]
      WantedBy=timers.target
  - path: /etc/systemd/system/sugarkube-self-heal@.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Self-heal automation for %I failures
      After=network-online.target

      [Service]
      Type=oneshot
      Environment=PYTHONUNBUFFERED=1
      ExecStart=/opt/sugarkube/self_heal_service.py --unit %I --reason "%I failure"
      StandardOutput=journal
      StandardError=journal
      SyslogIdentifier=sugarkube-self-heal
  # projects-start
  - path: /etc/systemd/system/projects-compose.service
    permissions: '0644'
    content: |
      [Unit]
      Description=token.place and dspace via docker compose
      Requires=docker.service
      After=docker.service network-online.target
      Wants=network-online.target
      OnFailure=sugarkube-self-heal@%n.service
      OnFailureJobMode=replace-irreversibly

      [Service]
      Type=oneshot
      WorkingDirectory=/opt/projects
      ExecStartPre=/opt/projects/init-env.sh
      ExecStart=/usr/bin/docker compose -f docker-compose.yml up -d
      ExecStop=/usr/bin/docker compose -f docker-compose.yml down
      RemainAfterExit=yes
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=multi-user.target
  - path: /etc/systemd/system/cloud-init.service.d/99-sugarkube-self-heal.conf
    permissions: '0644'
    content: |
      [Unit]
      OnFailure=sugarkube-self-heal@%n.service
      OnFailureJobMode=replace-irreversibly
  - path: /etc/systemd/system/cloud-config.service.d/99-sugarkube-self-heal.conf
    permissions: '0644'
    content: |
      [Unit]
      OnFailure=sugarkube-self-heal@%n.service
      OnFailureJobMode=replace-irreversibly
  - path: /etc/systemd/system/cloud-final.service.d/99-sugarkube-self-heal.conf
    permissions: '0644'
    content: |
      [Unit]
      OnFailure=sugarkube-self-heal@%n.service
      OnFailureJobMode=replace-irreversibly
  - path: /etc/systemd/system/k3s-ready.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Wait for k3s node readiness
      Requires=k3s.service
      Wants=network-online.target projects-compose.service
      After=k3s.service network-online.target projects-compose.service

      [Service]
      Type=oneshot
      ExecStart=/opt/sugarkube/k3s-ready.sh
      TimeoutStartSec=900
      RemainAfterExit=yes

      [Install]
      WantedBy=k3s-ready.target
  - path: /etc/systemd/system/k3s-ready.target
    permissions: '0644'
    content: |
      [Unit]
      Description=Projects compose and k3s readiness target
      Requires=projects-compose.service k3s-ready.service
      Wants=projects-compose.service k3s-ready.service
      After=projects-compose.service k3s-ready.service
      AllowIsolate=yes

      [Install]
      WantedBy=multi-user.target
  # projects-end
runcmd:
  - |
      bash -c '
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/debian/gpg | \
          gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        repo=https://download.docker.com/linux/debian
        echo "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] ${repo} bookworm stable" \
          > /etc/apt/sources.list.d/docker.list
        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io \
          docker-buildx-plugin docker-compose-plugin
      '
  - [bash, -c, 'id pi >/dev/null 2>&1 && usermod -aG docker pi || true']
  - [bash, -c, 'mkdir -p /opt/sugarkube']
  - [bash, -c, 'id pi >/dev/null 2>&1 && chown -R pi:pi /opt/sugarkube || true']
  - [bash, -c, 'install -m 0755 -d /etc/sugarkube/helm-bundles.d /opt/sugarkube/helm-values']
  - [bash, -c, 'mkdir -p /var/log/journal && systemctl restart systemd-journald']
  - [systemctl, daemon-reexec]   # reload systemd units
  - [systemctl, enable, --now, docker]
  - [bash, -c, 'curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -']
  - [/opt/projects/start-projects.sh]  # projects-runcmd
  - [systemctl, enable, k3s-ready.target]
  - [systemctl, start, k3s-ready.target]
  - [systemctl, enable, --now, sugarkube-helm-bundles.service]
  - [/opt/sugarkube/export-kubeconfig.sh]
  - [/opt/sugarkube/export-node-token.sh]
  - [bash, -c, 'apt-get autoremove -y']
  - [bash, -c, 'apt-get clean && rm -rf /var/lib/apt/lists/*']
  - |
      if grep -q 'TUNNEL_TOKEN=""' /opt/sugarkube/.cloudflared.env; then
        echo 'Cloudflare token missing; not starting tunnel'
      else
        systemctl enable --now cloudflared-compose.service
      fi
