apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../platform
  - ../../secrets/platform/cloudflare-api-token.enc.yaml
  - ../../secrets/platform/cloudflared-tunnel.enc.yaml
  - ../../secrets/platform/ghcr-read.enc.yaml
  - ../../secrets/platform/grafana-admin.enc.yaml
  - ../../secrets/storage/etcd-s3.enc.yaml
patches:
  - target:
      kind: DaemonSet
      name: kube-vip
      namespace: kube-system
    patch: |
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: kube-vip
        namespace: kube-system
      spec:
        template:
          spec:
            containers:
              - name: kube-vip
                env:
                  - name: address
                    value: 10.0.2.40
  - target:
      kind: HelmRelease
      name: cloudflared
      namespace: cloudflared
    patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      metadata:
        name: cloudflared
        namespace: cloudflared
      spec:
        values:
          tunnelID: 33333333-3333-3333-3333-333333333333
          ingress:
            - hostname: apps.sugarkube.cloud
              service: http://traefik.kube-system.svc.cluster.local:80
            - service: http_status:404
  - target:
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring
    patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      metadata:
        name: kube-prometheus-stack
        namespace: monitoring
      spec:
        values:
          grafana:
            grafana.ini:
              server:
                root_url: https://grafana.sugarkube.cloud
  - target:
      kind: ClusterIssuer
      name: letsencrypt-staging
    patch: |
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-staging
      spec:
        acme:
          email: ops@sugarkube.cloud
  - target:
      kind: ClusterIssuer
      name: letsencrypt-production
    patch: |
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-production
      spec:
        acme:
          email: ops@sugarkube.cloud
