apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: ">=51.0.0"
  values:
    grafana:
      adminPassword: admin
      ingress:
        enabled: false
    prometheus:
      prometheusSpec:
        retention: 15d
        enableAdminAPI: false
    alertmanager:
      alertmanagerSpec:
        replicas: 1
