apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-vip
      version: 0.5.12
      sourceRef:
        kind: HelmRepository
        name: kube-vip
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: kube-vip-values
      valuesKey: values.yaml
  values:
    config:
      enableServices: false
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
