apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - cloudflared
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
