apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - probes/public-blackbox.yaml
  - servicemonitors/traefik.yaml
  - servicemonitors/cloudflared.yaml
  - prometheusrules/app-uptime.yaml
