apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-credentials
  namespace: cloudflared
type: Opaque
stringData:
  credentials.json: ENC[AES256_GCM,data:cHJvZC1jcmVkcy5qc29u,iv:GL3dH0xHrFvtKRiH,tag:dtk8QFOZ4LM=,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1sugarkubeexample0syg4kktq0js0d9f0g7au5l5rlqedukzpc75q0ys4lc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRlZC12MQo=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-01T00:00:00Z"
  mac: ENC[AES256_GCM,data:KTzNaIQY1bkt,iv:3HTpA+MAnD58uh4L,tag:esNc6+/66ec=,type:str]
  encrypted_regex: '^(data|stringData)$'
  version: 3.8.1
