apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring
data:
  values.yaml: |
    fullnameOverride: kube-prometheus-stack
    prometheus:
      prometheusSpec:
        retention: 30d
        replicas: 2
        enableAdminAPI: false
        externalLabels:
          cluster: sugarkube-prod
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 100Gi
              storageClassName: longhorn
    grafana:
      admin:
        existingSecret: grafana-admin-credentials
      ingress:
        enabled: false
      serviceMonitor:
        selfMonitor: true
    alertmanager:
      config:
        global:
          resolve_timeout: 5m
        route:
          receiver: null-receiver
          group_by: [cluster, service]
        receivers:
          - name: null-receiver
    kubeEtcd:
      enabled: true
    kubeControllerManager:
      enabled: true
    kubeScheduler:
      enabled: true
