# Production-only non-Flux kube-prometheus-stack overrides.
defaultRules:
  disabled:
    Watchdog: true
prometheus:
  prometheusSpec:
    externalLabels:
      cluster: sugarkube-prod
alertmanager:
  alertmanagerSpec:
    secrets: []
  config:
    route:
      group_by: null
      group_wait: null
      group_interval: null
      repeat_interval: null
      receiver: "null"
      routes: []
    receivers:
      - name: "null"
    inhibit_rules: []
