apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    provider: cloudflare
    sources:
      - service
      - ingress
    domainFilters: []
    txtOwnerId: sugarkube
    cloudflare:
      apiTokenSecretRef:
        name: cloudflare-api-token
        key: api-token
    policy: sync
    serviceMonitor:
      enabled: true
