apiVersion: v1
kind: ConfigMap
metadata:
  name: external-dns-values
  namespace: external-dns
data:
  values.yaml: |
    provider: cloudflare
    logLevel: info
    policy: upsert-only
    domainFilters: []
    txtOwnerId: sugarkube
    image:
      repository: bitnami/external-dns
      tag: 0.14.2
    sources:
      - ingress
    extraEnvVars:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare
            key: api-token
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      additionalLabels:
        release: kube-prometheus-stack
