apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-credentials
  namespace: cloudflared
type: Opaque
stringData:
  credentials.json: ENC[AES256_GCM,data:GJHd2k5TbhqUH/xgQ9jBUA==,iv:RAdlvSxW8Qtyun8flB751w==,tag:RjF05Zby3CMLjrFitnSz2Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zdug0ycgysmxszysd9m3jdln5eu4jqk9hwaxz6c0er42m67h50ssgk9s0y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRlZC1kYXRhLXNpbXVsYXRlZAo=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-01T12:00:00Z"
  mac: ENC[AES256_GCM,data:XAaiqvQDoa0/CdAbhlukrw==,iv:wRfovqcsULIUt0Sp5h/BPA==,tag:yvTOpP/4nVhqNrwnPnYuug==,type:str]
  version: 3.8.0
