apiVersion: v1
kind: List
metadata:
  name: platform-helm-repositories
items:
  - apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: HelmRepository
    metadata:
      name: kube-vip
      namespace: flux-system
    spec:
      interval: 1h
      url: https://kube-vip.github.io/helm-charts
  - apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: HelmRepository
    metadata:
      name: jetstack
      namespace: flux-system
    spec:
      interval: 1h
      url: https://charts.jetstack.io
  - apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: HelmRepository
    metadata:
      name: cloudflare
      namespace: flux-system
    spec:
      interval: 1h
      url: https://cloudflare.github.io/helm-charts
  - apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: HelmRepository
    metadata:
      name: longhorn
      namespace: flux-system
    spec:
      interval: 1h
      url: https://charts.longhorn.io
  - apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: HelmRepository
    metadata:
      name: prometheus-community
      namespace: flux-system
    spec:
      interval: 1h
      url: https://prometheus-community.github.io/helm-charts
  - apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: HelmRepository
    metadata:
      name: grafana
      namespace: flux-system
    spec:
      interval: 1h
      url: https://grafana.github.io/helm-charts
  - apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: HelmRepository
    metadata:
      name: bitnami
      namespace: flux-system
    spec:
      interval: 1h
      url: https://charts.bitnami.com/bitnami
