apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
type: Opaque
stringData:
  age.agekey: ENC[AES256_GCM,data:QUdFX0tFWV9DT05URU5U,iv:NEpNdFJmS0lqcFlvYTBxWQ==,tag:T1ZsSlV4cnhjbnVCVDlHdw==,type:str]
sops:
  age:
    - recipient: age1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqs0p0s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRlZC1kYXRhCi0tLS0KRFZ3cjhYejA5WWdROUJ2UkI5WlRG
        V1BPL1J5ZFE2NStSdWR3ZXVmVzRkQlRjSmVBClE1VnU0eUNvWTg4NUZpR0Zy
        TjZ5dnpkR3BldDdQbUZzT1NmNzA0NmMKdUxLQ1dHZlVtYwotLS0tLUVuZCBP
        RiBBR0UgRU5DUllQVEVEIEZJTEUtLS0tLQo=
        -----END AGE ENCRYPTED FILE-----
  encrypted_regex: '^(data|stringData)$'
  mac: ENC[AES256_GCM,data:Q0ZIT2xUN3FXSHZycWF1Z0xqVjB3dz09,iv:T1MyaE1wVkVjTnpTQ0t3QQ==,tag:NG1zWk9PYmFxc2M1WlYzYw==,type:str]
  lastmodified: "2024-05-01T00:25:00Z"
  version: 3.7.3
