apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../
  - ../../storage/nfs-subdir-external-provisioner/helmrelease.yaml
patches:
  - target:
      kind: HelmRelease
      name: longhorn
      namespace: longhorn-system
    patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      metadata:
        name: longhorn
        namespace: longhorn-system
      spec:
        suspend: true
