apiVersion: v1
kind: Service
metadata:
  name: cloudflare-tunnel-metrics
  namespace: cloudflare
  labels:
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/instance: cloudflare-tunnel
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/instance: cloudflare-tunnel
  ports:
    - name: metrics
      port: 2000
      targetPort: 2000
