apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-subdir-external-provisioner-values
  namespace: kube-system
data:
  values.yaml: |
    nfs:
      server: 10.0.0.10
      path: /srv/nfs/k3s
    storageClass:
      create: true
      defaultClass: true
      name: nfs-client
      reclaimPolicy: Delete
      archiveOnDelete: false
