apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-credentials
  namespace: cloudflared
type: Opaque
stringData:
  credentials.json: ENC[AES256_GCM,data:aW50LWNsb3VkZmxhcmU=,iv:Wz5xg2YFcaPtdmZj,tag:6YcVkYQ+ToI=,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1sugarkubeexample0syg4kktq0js0d9f0g7au5l5rlqedukzpc75q0ys4lc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRlZC12MQo=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-01T00:00:00Z"
  mac: ENC[AES256_GCM,data:Yk58uYtqfRZy,iv:ZqbgtmGiXLxxYfV6,tag:LDb4pS0yWxQ=,type:str]
  encrypted_regex: '^(data|stringData)$'
  version: 3.8.1
