apiVersion: v1
kind: Secret
metadata:
  name: ghcr-read-secret
  namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:9DQSzyTIlDeA2Oyt+RQ2tA==,iv:vh8XpT+T3x62udiW03om/A==,tag:5OMp1h7KBNzCk6eYdedDaQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zdug0ycgysmxszysd9m3jdln5eu4jqk9hwaxz6c0er42m67h50ssgk9s0y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRlZC1kYXRhLXNpbXVsYXRlZAo=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-01T12:00:00Z"
  mac: ENC[AES256_GCM,data:aVVSZRMxc+KXhJHAkI5jBQ==,iv:kf/duRoOYJXR5JdBwbG7XA==,tag:FlZLCpHoE15AlYQ4DU8mmA==,type:str]
  version: 3.8.0
