apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:aW50LWFkbWlu,iv:YN3J0Y0gkDxR6GMg,tag:coWsFA07XSc=,type:str]
  admin-password: ENC[AES256_GCM,data:aW50LXNlY3JldA==,iv:Q82iDu96o8gG2JoN,tag:mcEjl5nZp3Y=,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1sugarkubeexample0syg4kktq0js0d9f0g7au5l5rlqedukzpc75q0ys4lc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRlZC12MQo=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-01T00:00:00Z"
  mac: ENC[AES256_GCM,data:ptM5j8x2zEwD,iv:gOGrVX+hj+5K1EVV,tag:udm9h9Qz9og=,type:str]
  encrypted_regex: '^(data|stringData)$'
  version: 3.8.1
