apiVersion: v1
kind: Secret
metadata:
  name: etcd-s3-credentials
  namespace: kube-system
type: Opaque
stringData:
  endpoint: ENC[AES256_GCM,data:5eyRMXvTjENRTNuZ9oticg==,iv:xe/AXJQk/J/9A1YdUdvGqQ==,tag:6f7SZQLtKh9/9EkLLGR1GQ==,type:str]
  bucket: ENC[AES256_GCM,data:DJqW6zx2bS87bbPzX369dg==,iv:balDyUiPn8+LT2iGha1ssA==,tag:tFd2pQbKaUdNGSIiNbPO6Q==,type:str]
  access-key: ENC[AES256_GCM,data:p/7hPkBCL7o4lRRrfLCvdw==,iv:fAfmezpF92IqqEdESV5VIQ==,tag:mBrIp38mQIgqSK0whpxJhQ==,type:str]
  secret-key: ENC[AES256_GCM,data:OetSmg7LNHOSXJzbxTN3Yg==,iv:20K03aY5s8OpniAe+zftGA==,tag:wpTIH/5c2zvT9Y0z6zU6Jw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1zdug0ycgysmxszysd9m3jdln5eu4jqk9hwaxz6c0er42m67h50ssgk9s0y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRlZC1kYXRhLXNpbXVsYXRlZAo=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-01T12:00:00Z"
  mac: ENC[AES256_GCM,data:Qzv7i0kHp6jNPtmTh9M7tg==,iv:2Q/CrDxT1wxjwOeq3qsj5w==,tag:U83vv6j07J8uID6AqFFoBg==,type:str]
  version: 3.8.0
