apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  values:
    config:
      vip_config:
        address: 10.2.0.40
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  values:
    tunnelName: prod-sugarkube
    ingress:
      - hostname: "*.prod.sugarkube.example.com"
        service: http://traefik.ingress-system.svc.cluster.local:80
      - service: http_status:404
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  values:
    defaultSettings:
      backupTarget: s3://prod-sugarkube-longhorn
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: sre+prod@sugarkube.example
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: sre+prod@sugarkube.example
