apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: cloudflared
spec:
  interval: 30m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: ">=6.30.0"
  values:
    provider: cloudflare
    cloudflare:
      apiTokenSecretRef:
        name: cloudflare-api-token
        key: api-token
    policy: sync
    txtOwnerId: sugarkube
    sources:
      - service
      - ingress
    interval: 1m
