apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack-values.yaml
  - kube-prometheus-stack.yaml
  - loki-values.yaml
  - loki.yaml
  - promtail-values.yaml
  - promtail.yaml
  - traefik-servicemonitor.yaml
