apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-values
  namespace: monitoring
data:
  values.yaml: |
    deploymentMode: SingleBinary
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      auth_enabled: false
      schemaConfig:
        configs:
          - from: 2024-01-01
            store: boltdb-shipper
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
    persistence:
      enabled: true
      size: 50Gi
      storageClassName: longhorn
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
