apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-blackbox-exporter-values
  namespace: monitoring
data:
  values.yaml: |
    fullnameOverride: prometheus-blackbox-exporter
    serviceMonitor:
      enabled: true
      defaults:
        labels:
          release: kube-prometheus-stack
    config:
      modules:
        https_2xx:
          prober: http
          timeout: 10s
          http:
            method: GET
            follow_redirects: true
            fail_if_not_ssl: true
            fail_if_ssl: false
            valid_status_codes: [200]
            preferred_ip_protocol: ip4
            tls_config:
              insecure_skip_verify: false
        json_health_2xx:
          prober: http
          timeout: 10s
          http:
            method: GET
            follow_redirects: true
            fail_if_not_ssl: true
            valid_status_codes: [200]
            fail_if_body_not_matches_regexp:
              - '(?s)^[[:space:]]*\{.{0,1000}\}[[:space:]]*$'
            preferred_ip_protocol: ip4
            tls_config:
              insecure_skip_verify: false
        static_content_2xx:
          prober: http
          timeout: 10s
          http:
            method: GET
            follow_redirects: true
            fail_if_not_ssl: true
            valid_status_codes: [200]
            fail_if_body_not_matches_regexp:
              - '(?s).{1,1000}'
            preferred_ip_protocol: ip4
            tls_config:
              insecure_skip_verify: false
