apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-values
  namespace: monitoring
data:
  values.yaml: |
    config:
      clients:
        - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
      snippets:
        pipelineStages:
          - cri: {}
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
