apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
resources:
  - https://github.com/fluxcd/flux2/releases/download/v2.2.3/install.yaml
patches:
  - target:
      kind: Kustomization
      name: flux-system
    patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        interval: 1m
        prune: true
        retryInterval: 1m
        timeout: 5m
