apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/fluxcd/flux2//manifests/install?ref=v2.2.3
patches:
  - target:
      kind: Deployment
      name: source-controller
      namespace: flux-system
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: source-controller
      spec:
        template:
          spec:
            containers:
              - name: manager
                env:
                  - name: RUNTIME_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
