apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: ssh://git@github.com/sugarkube/platform.git
  secretRef:
    name: flux-git-deploy
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # The bootstrap script patches this path per-environment after bootstrap.
  path: ./clusters/prod
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: platform-settings
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: traefik
      namespace: kube-system
    - apiVersion: apps/v1
      kind: Deployment
      name: cloudflared
      namespace: cloudflared
    - apiVersion: apps/v1
      kind: StatefulSet
      name: prometheus-kube-prometheus-stack-prometheus
      namespace: monitoring
    - apiVersion: apps/v1
      kind: StatefulSet
      name: alertmanager-kube-prometheus-stack-alertmanager
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: longhorn-driver-deployer
      namespace: longhorn-system
