apiVersion: v1
kind: List
items:
  - apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    metadata:
      name: flux-system
      namespace: flux-system
    spec:
      interval: 1m
      ref:
        branch: main
      url: ssh://git@github.com/sugarkube/platform.git
      secretRef:
        name: flux-git-deploy
  - apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: platform
      namespace: flux-system
    spec:
      interval: 5m
      prune: true
      wait: true
      sourceRef:
        kind: GitRepository
        name: flux-system
      # The bootstrap script patches this path to the selected environment after bootstrap.
      path: ./clusters/prod
      decryption:
        provider: sops
        secretRef:
          name: sops-age
      postBuild:
        substituteFrom:
          - kind: Secret
            name: platform-settings
