# Copy this file and update device paths, Wi-Fi, and SSH keys before running
# `python -m sugarkube_toolkit pi cluster --config <path>`.

[image]
dir = "~/sugarkube/images"
name = "sugarkube.img"

[image.workflow]
trigger = true
clone_token_place = true
clone_dspace = true

[defaults]
# Provide an SSH key that should be authorized on every node.
ssh_authorized_keys = ["ssh-ed25519 AAAA... your-key-comment"]
# Configure Wi-Fi for all nodes (override per-node with [[nodes]].wifi).
[defaults.wifi]
ssid = "YourNetwork"
psk = "SuperSecretPassphrase"
country = "US"

[[nodes]]
name = "controller"
device = "/dev/sdX"
hostname = "sugar-control"
role = "control-plane"
report_dir = "~/sugarkube/reports/cluster/controller"

[[nodes]]
name = "worker-a"
device = "/dev/sdY"
hostname = "sugar-worker-a"
role = "worker"

[[nodes]]
name = "worker-b"
device = "/dev/sdZ"
hostname = "sugar-worker-b"
role = "worker"

[cluster.join]
server = "sugar-control.local"
agents = ["sugar-worker-a.local", "sugar-worker-b.local"]
apply = true
apply_wait = true
apply_wait_timeout = 420
# Forward additional rehearsal arguments here, e.g.:
# extra_args = ["--agent-user", "pi", "--identity", "~/.ssh/id_ed25519"]
