apiVersion: v1
kind: Service
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
  labels:
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/instance: cloudflare-tunnel
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/instance: cloudflare-tunnel
  ports:
    - name: metrics
      port: 2000
      targetPort: 2000
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-tunnel
      app.kubernetes.io/instance: cloudflare-tunnel
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - cloudflare
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-tunnel
      app.kubernetes.io/instance: cloudflare-tunnel
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s

