apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: longhorn-system
spec:
  interval: 30m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
        namespace: flux-system
      version: ">=4.0.18"
  values:
    nfs:
      # Override these values per environment via a strategic merge patch.
      server: 192.168.1.10
      path: /srv/nfs/sugarkube
    storageClass:
      create: false
