name: Docs
on:
  push:
    paths:
      - 'docs/**'
      - 'README.md'
  pull_request:
    paths:
      - 'docs/**'
      - 'README.md'
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  spellcheck:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.head.repo.full_name == github.repository) ||
      (github.event_name == 'pull_request_target' &&
       github.event.pull_request.head.repo.full_name != github.repository)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: github.event_name != 'pull_request_target'
        uses: actions/checkout@v5
      - name: Checkout pull request head
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install aspell dictionaries
        run: sudo apt-get update && sudo apt-get install -y aspell aspell-en
      - name: Spell check markdown & docs
        uses: rojopolis/spellcheck-github-actions@0.35.0
        with:
          config_path: .spellcheck.yaml
  linkcheck:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.head.repo.full_name == github.repository) ||
      (github.event_name == 'pull_request_target' &&
       github.event.pull_request.head.repo.full_name != github.repository)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: github.event_name != 'pull_request_target'
        uses: actions/checkout@v5
      - name: Checkout pull request head
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: astral-sh/setup-uv@v1
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - run: |
          uv pip install --system linkchecker
          linkchecker --no-warnings README.md docs/
