name: KiCad CI
on:
  push:
    paths: ['elex/**/*.kicad_sch', 'elex/**/*.kicad_pcb']

jobs:
  kicad-export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install KiCad
        run: |
          sudo apt-get update
          sudo apt-get install -y kicad
      - name: Generate outputs
        run: bash scripts/kicad_export.sh elex/power_ring/power_ring.kicad_pcb
      - uses: actions/upload-artifact@v4
        with:
          name: kicad-build
          path: kicad-export/**
