name: KiCad CI
on:
  push:
    paths:
      - 'elex/**/*.kicad_*'

jobs:
  kibot:
    runs-on: ubuntu-latest
    # Kibot action pulls its own container image with KiCad + Python
    steps:
      - uses: actions/checkout@v4

      - name: Install KiCad
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-7.0-releases
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y kicad kicad-cli

      - name: Export KiCad files
        uses: actions-for-kicad/generate-kicad-files@v1.1
        with:
          schematic_pdf: true
          gerber: true
          bom: true

      - name: Fabricate board with KiBot
        # Use a container image with KiCad 9 to open the project
        uses: INTI-CMNB/kibot@v2_k9
        with:
          board: elex/power_ring/power_ring.kicad_pcb
          config: .kibot/power_ring.yaml
          dir: build/power_ring

      - name: Upload fab outputs
        uses: actions/upload-artifact@v4
        with:
          name: power_ring-fab
          path: |
            build/power_ring/**/*.zip
            build/power_ring/**/*.pdf
