name: pi-image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable universe repository
        run: sudo add-apt-repository -y universe
      - name: Install pi-gen dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: >-
            quilt qemu-user-static debootstrap libarchive-tools arch-test
      - name: Build Raspberry Pi OS image
        env:
          ARM64: 1
        run: sudo ./scripts/build_pi_image.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sugarkube-img
          path: sugarkube.img.xz
