name: pi-image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Free up disk space
        run: |
          sudo apt-get clean
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc \
            /opt/hostedtoolcache /usr/local/lib/node_modules \
            /usr/local/share/boost
          docker system prune -af || true
          df -h
      - name: Install pi-gen dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            quilt qemu-user-static debootstrap libarchive-tools arch-test
      - name: Compute pi-gen cache key
        id: pigen-key
        run: |
          ref=$(git ls-remote https://github.com/RPi-Distro/pi-gen.git refs/heads/bookworm | cut -f1)
          echo "key=pigen-${RUNNER_OS}-bookworm-${ref}-$(date +'%Y-%m')" >> "$GITHUB_OUTPUT"
      - name: Restore pi-gen Docker image
        id: cache-pigen
        uses: actions/cache@v4
        with:
          path: ~/cache/pi-gen.tar
          key: ${{ steps.pigen-key.outputs.key }}
      - name: Load cached pi-gen image
        if: steps.cache-pigen.outputs.cache-hit == 'true'
        run: docker load -i ~/cache/pi-gen.tar
      - name: Build Raspberry Pi OS image
        env:
          ARM64: 1
        run: sudo ./scripts/build_pi_image.sh
      - name: Save pi-gen Docker image
        if: steps.cache-pigen.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/cache
          docker image save pi-gen:latest -o ~/cache/pi-gen.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sugarkube-img
          path: sugarkube.img.xz
