name: pi-image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pi-gen dependencies
        run: |
          sudo add-apt-repository -y universe
          sudo apt-get update
          sudo apt-get install -y \
            quilt qemu-user-static debootstrap libarchive-tools arch-test
      - name: Build Raspberry Pi OS image
        run: sudo ./scripts/build_pi_image.sh
      - name: Compress image
        run: xz -9 --keep sugarkube.img
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sugarkube-img
          path: sugarkube.img.xz
