name: Test Suite
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup uv
        uses: astral-sh/setup-uv@v1
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          uv pip install --system pytest pytest-cov coverage requests-mock
          if [ -f requirements.txt ]; then uv pip install --system -r requirements.txt; fi
      - name: Run tests with coverage
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest --cov=scripts/download_latest_image.py \
            --cov-report=xml --cov-report=term --cov-fail-under=85 --maxfail=1 \
            --disable-warnings -q
      - name: Upload coverage
        if: hashFiles('coverage.xml') != ''
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: python
          fail_ci_if_error: true
