name: Test Suite
on:
  push:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}
      - name: Setup uv
        uses: astral-sh/setup-uv@v1
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          uv pip install --system pytest pytest-cov coverage
          if [ -f requirements.txt ]; then uv pip install --system -r requirements.txt; fi
      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=xml --cov-report=term --maxfail=1 --disable-warnings -q
      - name: Upload coverage
        if: >-
          ${{ hashFiles('coverage.xml') != '' &&
              secrets.CODECOV_TOKEN != '' &&
              (github.event_name != 'pull_request_target' || github.event.pull_request.head.repo.fork == false) }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: python
          fail_ci_if_error: true
